use std::sync::Arc;
use std::time::Duration;

use thiserror::Error;
use tokio::task::JoinHandle;

use crate::error::DiagnosticSummary;
use crate::execution::UserInput;
use crate::execution::{ConfigRevision, ExecutionConfig};
use crate::history::{HistoryItem, estimate_history_bytes};
use crate::ids::LoopId;
use crate::limits::LoopLimits;
use crate::model::{MAX_MODEL_CALL_TIMEOUT, MAX_MODEL_RETRY_DELAY, Usage};

mod control;
mod event;
mod handle;
mod runner;
mod state;

pub use event::{LoopEvent, LoopEventEnvelope, LoopEventStream, LoopOutcomeSummary, OutputChannel};
pub use handle::LoopHandle;
pub use state::{LoopState, LoopStatus};

use control::LoopControl;

const MAX_TOOL_ROUNDS: u16 = 1_024;
const MAX_PENDING_STEERS: usize = 64;
const MAX_EVENT_CAPACITY: usize = 4_096;
/// The reused model driver only honors up to four delivery retries; the public
/// validation below enforces the same ceiling as `start`.
const MAX_MODEL_RETRY_ATTEMPTS: u8 = 4;

/// Options for one agent loop.
///
/// All fields are public; start from [`LoopOptions::default_checked`] and
/// mutate only what the call site needs. There is deliberately no builder.
#[derive(Clone, Debug)]
pub struct LoopOptions {
    pub deadline: Option<tokio::time::Instant>,
    pub max_tool_rounds: u16,
    pub max_pending_steers: usize,
    pub event_capacity: usize,
    pub prompt_timeout: Duration,
    pub model_timeout: Duration,
    pub policy_timeout: Duration,
    pub tool_timeout: Duration,
    pub model_retry_attempts: u8,
    pub model_retry_base_delay: Duration,
    pub limits: LoopLimits,
}

impl LoopOptions {
    pub fn default_checked() -> Result<Self, LoopStartError> {
        let options = Self {
            deadline: None,
            max_tool_rounds: 32,
            max_pending_steers: 16,
            event_capacity: 256,
            prompt_timeout: Duration::from_secs(30),
            model_timeout: Duration::from_secs(10 * 60),
            policy_timeout: Duration::from_secs(30),
            tool_timeout: Duration::from_secs(30 * 60),
            model_retry_attempts: 2,
            model_retry_base_delay: Duration::from_millis(100),
            limits: LoopLimits::default(),
        };
        options.validate()?;
        Ok(options)
    }

    pub fn validate(&self) -> Result<(), LoopStartError> {
        if !(1..=MAX_TOOL_ROUNDS).contains(&self.max_tool_rounds)
            || !(1..=MAX_PENDING_STEERS).contains(&self.max_pending_steers)
            || !(1..=MAX_EVENT_CAPACITY).contains(&self.event_capacity)
            || self.prompt_timeout.is_zero()
            || self.model_timeout.is_zero()
            || self.model_timeout > MAX_MODEL_CALL_TIMEOUT
            || self.policy_timeout.is_zero()
            || self.tool_timeout.is_zero()
            || self.model_retry_attempts == 0
            || self.model_retry_attempts > MAX_MODEL_RETRY_ATTEMPTS
            || self.model_retry_base_delay.is_zero()
            || self.model_retry_base_delay > MAX_MODEL_RETRY_DELAY
            || self
                .deadline
                .is_some_and(|deadline| deadline <= tokio::time::Instant::now())
        {
            return Err(LoopStartError::InvalidOptions);
        }
        self.limits
            .validate()
            .map_err(|_| LoopStartError::InvalidOptions)
    }
}

/// Everything the runner needs for one task: host history, the fresh user
/// input, and the immutable execution snapshot. `LoopId` is generated by
/// `AgentLoop::start`; do not place this new input into `history`.
#[derive(Clone)]
pub struct LoopRequest {
    pub history: Arc<[HistoryItem]>,
    pub input: UserInput,
    pub config: ExecutionConfig,
}

impl LoopRequest {
    pub fn new(history: Arc<[HistoryItem]>, input: UserInput, config: ExecutionConfig) -> Self {
        Self {
            history,
            input,
            config,
        }
    }
}

/// Owner of one running agent loop. A loop runs exactly once; dropping the
/// owner cancels it best-effort without blocking.
#[must_use = "dropping AgentLoop cancels the running loop"]
pub struct AgentLoop {
    control: Arc<LoopControl>,
    events: Option<LoopEventStream>,
    join: Option<JoinHandle<Arc<LoopReport>>>,
}

impl AgentLoop {
    pub fn start(request: LoopRequest, options: LoopOptions) -> Result<Self, LoopStartError> {
        tokio::runtime::Handle::try_current().map_err(|_| LoopStartError::NoTokioRuntime)?;
        options.validate()?;
        // Same config-vs-LoopLimits validation as `LoopHandle::update`: the
        // initial config must satisfy the loop's runtime budgets too.
        request
            .config
            .validate_against_limits(&options.limits)
            .map_err(|_| LoopStartError::InvalidConfig)?;
        let input_bytes = request.input.as_text().len();
        if input_bytes == 0 || input_bytes > options.limits.max_user_input_bytes {
            return Err(LoopStartError::InvalidInput);
        }
        if request.history.len() > options.limits.max_history_items
            || estimate_history_bytes(&request.history) > options.limits.max_history_bytes
        {
            return Err(LoopStartError::HistoryTooLarge);
        }

        let id = LoopId::new().map_err(|_| LoopStartError::IdGeneration)?;
        let options = Arc::new(options);
        let (control, sink, events, completion_tx) = LoopControl::new(
            id,
            options.event_capacity,
            options.limits,
            options.max_pending_steers,
        )
        .map_err(|_| LoopStartError::InvalidOptions)?;
        let control = Arc::new(control);

        let join = tokio::spawn(runner::run_loop(
            request,
            options,
            Arc::clone(&control),
            sink,
            completion_tx,
        ));

        Ok(Self {
            control,
            events: Some(events),
            join: Some(join),
        })
    }

    pub fn id(&self) -> LoopId {
        self.control.id
    }

    pub fn handle(&self) -> LoopHandle {
        LoopHandle::new(Arc::clone(&self.control))
    }

    pub fn take_events(&mut self) -> Result<LoopEventStream, TakeEventsError> {
        self.events.take().ok_or(TakeEventsError::AlreadyTaken)
    }

    /// Waits for the loop to finish without cancelling it. Returns the same
    /// `Arc<LoopReport>` as `LoopHandle::wait`.
    pub async fn join(mut self) -> Result<Arc<LoopReport>, LoopJoinError> {
        let Some(join) = self.join.take() else {
            return Err(LoopJoinError::TaskCancelled);
        };
        join.await.map_err(|_| LoopJoinError::TaskCancelled)
    }

    /// Cancels and waits for the runner task, returning its final report.
    pub async fn shutdown(mut self) -> Result<Arc<LoopReport>, LoopJoinError> {
        self.control
            .mark_cancel(crate::agent_loop::CancelReason::Shutdown);
        let join = self.join.take().ok_or(LoopJoinError::TaskCancelled)?;
        join.await.map_err(|_| LoopJoinError::TaskCancelled)
    }
}

impl Drop for AgentLoop {
    fn drop(&mut self) {
        self.control.mark_cancel(CancelReason::OwnerDropped);
    }
}

/// Incremental result of one finished agent loop.
///
/// `appended` holds only items this loop produced in memory; the host decides
/// when, whether, and how to persist them.
#[derive(Clone, Debug)]
pub struct LoopReport {
    pub loop_id: LoopId,
    pub outcome: LoopOutcome,
    pub appended: Arc<[HistoryItem]>,
    pub usage: Usage,
    pub requests: u32,
    pub tool_rounds: u16,
    pub final_config_revision: ConfigRevision,
}

#[derive(Clone, Debug, PartialEq)]
pub enum LoopOutcome {
    Completed,
    Cancelled(CancelReason),
    Failed(LoopFailure),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CancelReason {
    User,
    OwnerDropped,
    Shutdown,
    Deadline,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LoopFailure {
    pub kind: LoopFailureKind,
    pub diagnostic: DiagnosticSummary,
}

#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LoopFailureKind {
    Prompt,
    Model,
    InvalidModelResponse,
    OutputLimit,
    Refused,
    ContentFiltered,
    Policy,
    Interaction,
    MaxToolRounds,
    Internal,
}

/// Errors that prevent an agent loop from starting.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum LoopStartError {
    #[error("starting an agent loop requires a running Tokio runtime")]
    NoTokioRuntime,
    #[error("loop options are invalid")]
    InvalidOptions,
    #[error("execution config is invalid")]
    InvalidConfig,
    #[error("loop input is invalid")]
    InvalidInput,
    #[error("history exceeds the configured loop limits")]
    HistoryTooLarge,
    #[error("loop id generation failed")]
    IdGeneration,
}

/// Errors answering a pending interaction.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum AnswerError {
    #[error("no interaction is pending for this loop")]
    InteractionNotFound,
    #[error("interaction id or answer kind does not match the pending interaction")]
    WrongInteraction,
    #[error("the loop is not accepting interaction answers")]
    NotActive,
}

/// Errors accepting an execution config update.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum UpdateError {
    #[error("config does not satisfy the loop limits")]
    InvalidConfig,
    #[error("the loop is not accepting config updates")]
    NotActive,
}

/// Errors steering a running loop.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum SteerError {
    #[error("steer input exceeds the loop limits")]
    InvalidInput,
    #[error("the steer queue is full")]
    QueueFull,
    #[error("the loop is waiting for an interaction answer")]
    WaitingForInput,
    #[error("the loop is not accepting steers")]
    NotActive,
}

#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum LoopWaitError {
    #[error("the loop completion channel closed before a report was delivered")]
    CompletionClosed,
}

#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum LoopJoinError {
    #[error("the runner task was cancelled externally")]
    TaskCancelled,
}

#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum TakeEventsError {
    #[error("the loop event stream was already taken")]
    AlreadyTaken,
}
